services:
  redis:
    image: redis:7-alpine
    container_name: bag-counter-redis
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


  api:
    build: .
    container_name: bag-counter-api

    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000

    ports:
      - "8000:8000"

    volumes:
      - ./data:/app/data

    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1

    depends_on:
      redis:
        condition: service_healthy

    restart: unless-stopped


  worker:
    build: .
    container_name: bag-counter-worker

    command: >
      celery
      -A app.worker.celery_app.celery_app
      worker
      --loglevel=info
      --concurrency=1

    volumes:
      - ./data:/app/data

    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1

    depends_on:
      redis:
        condition: service_healthy

    gpus: all

    restart: unless-stopped